version: "3.9"
services:
  analysisDb:
    image: postgres:11
    restart: "always"
    ports: 
      - "5432:5432"
    volumes:
      - ./sql/analysisDb_create_tables.sql:/docker-entrypoint-initdb.d/analysisDb_create_tables.sql
      - ./sql/analysisDb_fill_tables.sql:/docker-entrypoint-initdb.d/analysisDb_fill_tables.sql
    environment:
      POSTGRES_DB: "analysisDb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123456"
    networks:
      - local

  queue:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - local
    
  analysis-app:
    build: ./analysis-app
    container_name: analysis-app-container
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - local

  analysis-deliver:
    build: ./AnalysisDelivery
    container_name: analysis-deliver-container
    ports:
      - "8081:80"
    networks:
      - local

  analysis-consumer:
    build: ./AnalysisConsumer
    container_name: analysis-consumer-container
    environment:
      - HOSTNAMERABBIT=rabbitmq
    restart: on-failure
    depends_on:
      - queue
    networks:
      - local
    stdin_open: true 

  analysis-register:
    build: ./AnalysisRegister
    container_name: analysis-register-container
    ports:
      - "8082:80"
    networks:
      - local

networks:
  local:
    driver: bridge